name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # Rigenera le card automaticamente ogni giorno a mezzanotte
  workflow_dispatch: # Ti permette di far partire l'aggiornamento anche a mano

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: mtdeve
