name: GitHub-Profile-Summary-Cards

on:
  push:
    branches:
      - main # on push
  schedule:
    - cron: "0 0 * * *" # every day at 00h
  workflow_dispatch: # also manual
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: mtdeve
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
